### PR TITLE
Update PoolsConfigDefault.ps1

### LINKED ISSUE #1357: [BUG] EnableAutoCoin removed on restart
I changed all pool to EnableAutoCoin: 1 correctly in my pools.config.txt but on restart, these get removed.

My guess is it's being reset for autoexchange pools, but it should be allowed for -coins pools, i.e. MPB and Zerg

### PR DESCRIPTION
**Pull request by talentoscope**
Remove autoexchange from -coins pools, since these are designed for wallet holders.
Fixes #1357

### CODE REVIEW

**Comment by talentoscope** [comment]
Actually, to enable this properly due to config changes, these should probably be explicitly set to $false

**Comment by RainbowMiner** [comment]
I'll have a closer look. As far as I remember, I had a special intention with this flag, probably for calculations in the pool modules. But I am not sure :)

**Comment by talentoscope** [comment]
Okay mate :)

**Comment by RainbowMiner** [comment]
Ok, I have checked this - it's exclusively to know for which pools the "EnableAutoCoin" isn't allowed. But since *coins pools can be used for either autoexchange or wallets, your pull request totally makes sense.

**Pull request merged**
