### PR TITLE
Add phi-phi-pool.com

### PR DESCRIPTION
**Pull request by xiaolin1579**
Add phi-phi-pool.com

### CODE REVIEW

**Comment by RainbowMiner** [comment]
Ok, I'll re-add phi-phi-pool.com - I had removed it last year, because the project appeared to be dead.

**Review by MONIMAKER365 — APPROVED** [review]
good job 👍🏽

**Comment by xiaolin1579** [comment]
> Ok, I'll re-add phi-phi-pool.com - I had removed it last year, because the project appeared to be dead.

Yes, they are back now.

**Comment by RainbowMiner** [comment]
Ok, re-added.

**Comment by xiaolin1579** [comment]
thank you.

**Pull request closed without merging**
